'use strict';
const by=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n=(x,d=0)=>x==null?'—':Number(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const pct=x=>x==null?'—':n(100*x,1)+'%';
const norm=x=>String(x).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const pos=x=>({'1':'P','2':'C','3':'1B','4':'2B','5':'3B','6':'SS','7':'LF','8':'CF','9':'RF','10':'DH','Y':'OF'}[x]??x??'Unknown');
const lawNames={associated:'Linked workload + hitting counts',independent:'Independent hitting counts',normal:'Previous Normal law',fixed:'Playing-time uncertainty only'};
let meta,data=[],history={},filtered=[],page=0,sort='value',descending=true,loadToken=0,detailToken=0,currentRow=null;
const size=40;
async function get(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path+' failed ('+r.status+')');return r.json();}
function options(id,values,label,keep=''){by(id).replaceChildren();by(id).add(new Option(label,''));for(const v of values)by(id).add(new Option(v,v));if(values.includes(keep))by(id).value=keep;}
function range(r,arm=by('law').value){return r.ranges[arm];}
async function loadYear(){const token=++loadToken;const y=+by('year').value;by('loadError').textContent='';by('rows').innerHTML='<tr><td colspan="11">Loading '+y+' forecasts…</td></tr>';try{const z=await get('years/'+y+'.json');if(token!==loadToken)return;data=z.rows;history=z.history;options('org',[...new Set(data.map(r=>r.org))].sort(),'All organizations',by('org').value);options('stage',[...new Set(data.map(r=>r.stage))].sort(),'All stages',by('stage').value);by('orgLabel').textContent=(y-1)+' organization (reconstructed)';by('timing').textContent='Predicting '+y+' from statistics through '+(y-1)+' and prospect rankings available '+meta.information_dates[String(y)]+'. Organizations are origin-year reconstructions, not future teams; unknown affiliations remain included.';render();}catch(e){if(token===loadToken){by('loadError').textContent='Could not load the research data: '+e.message;data=[];history={};render();}}}
function render(reset=true){if(reset)page=0;const actual=by('actual').checked,query=norm(by('search').value.trim()),org=by('org').value,stage=by('stage').value,evidence=by('evidence').value;
filtered=data.filter(r=>(!org||r.org===org)&&(!stage||r.stage===stage)&&(!query||norm(r.player_name).includes(query)||String(r.player_id).includes(query))&&(!evidence||evidence==='reviewed'&&r.reviewed||evidence==='missing'&&r.calibration_people===0||evidence==='sparse'&&r.calibration_people<20||evidence==='public'&&r.public_match));
filtered.sort((a,b)=>{const av=a[sort],bv=b[sort];if(av==null)return bv==null?0:1;if(bv==null)return -1;const c=typeof av==='string'?av.localeCompare(bv):av-bv;return (descending?-c:c)||a.player_id-b.player_id;});page=Math.max(0,Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1)));
document.querySelectorAll('.actualcol').forEach(e=>e.classList.toggle('hidden',!actual));
const sum=k=>filtered.reduce((s,r)=>s+(r[k]??0),0);
by('totals').innerHTML=[['Players',filtered.length,0],['Expected MLB PA',sum('pa'),0],['Expected offense',sum('value'),2],...(actual?[['Actual MLB PA',sum('next_pa'),0],['Actual offense',sum('next_value'),2]]:[])].map(([label,x,d])=>'<p><strong>'+n(x,d)+'</strong>'+label+'</p>').join('');
by('rows').innerHTML=filtered.slice(page*size,(page+1)*size).map(r=>{const a=range(r);return '<tr><td><button type="button" class="player" data-row="'+r.row_id+'">'+esc(r.player_name)+'</button><span class="sub">'+esc(pos(r.position))+' · '+r.player_id+' · age '+n(r.age,0)+'<br>'+esc(r.org)+'</span></td><td><span class="pill">'+esc(r.stage)+'</span></td>'+[n(r.rate,2),pct(r.p),n(r.pa),n(r.value,2),n(a[0],2)+' to '+n(a[2],2)].map(v=>'<td class="num">'+v+'</td>').join('')+(actual?[n(r.next_pa),n(r.next_rate,2),n(r.next_value,2)].map(v=>'<td class="num">'+v+'</td>').join(''):'')+'<td><span class="'+(r.calibration_people<20?'warning':'')+'">'+(r.calibration_people===0?'No risk-profile matches':n(r.calibration_people)+' risk matches')+'</span>'+(r.reviewed?'<span class="sub">Player review available</span>':'')+'</td></tr>';}).join('')||'<tr><td colspan="11">No matching players. Try another season, organization or evidence filter.</td></tr>';
by('page').textContent=n(filtered.length)+' players · page '+(page+1)+' of '+Math.max(1,Math.ceil(filtered.length/size));by('prev').disabled=page===0;by('next').disabled=(page+1)*size>=filtered.length;
for(const b of document.querySelectorAll('[data-sort]')){b.textContent=b.textContent.replace(/ [↑↓]$/,'')+(b.dataset.sort===sort?(descending?' ↓':' ↑'):'');b.closest('th').setAttribute('aria-sort',b.dataset.sort===sort?(descending?'descending':'ascending'):'none');}
if(currentRow&&by('detail').open)detail(currentRow,false);
}
function historyTable(rows){return '<div class="tablewrap"><table><thead><tr><th>Season</th><th>Level</th><th class="num">PA</th><th class="num">HR</th><th class="num">UBB</th><th class="num">K</th><th class="num">2B</th><th class="num">3B</th><th class="num">BABIP hits / chances</th></tr></thead><tbody>'+rows.map(h=>'<tr><td>'+h[0]+'</td><td>'+esc(h[1])+'</td>'+h.slice(2,8).map(v=>'<td class="num">'+n(v)+'</td>').join('')+'<td class="num">'+n(h[8])+' / '+n(h[9])+'</td></tr>').join('')+'</tbody></table></div>';}
async function detail(r,open=true){currentRow=r;const token=++detailToken,actual=by('actual').checked;by('detailTitle').textContent=r.player_name;by('detailSubtitle').textContent='Forecast '+r.target_year+' · stats through '+r.origin_year+' · '+r.org+' · '+pos(r.position)+' · MLBAM '+r.player_id;
let html='<div class="facts">'+[['Batting /600',n(r.rate,3)],['Any MLB PA',pct(r.p)],['PA if active',n(r.conditional_pa,1)],['Expected PA',n(r.pa,1)],['Expected offense',n(r.value,3)],['Age at origin',n(r.age,0)]].map(([label,value])=>'<div class="fact"><span>'+label+'</span><strong>'+value+'</strong></div>').join('')+'</div>';
html+='<h3>How the forecast adds up</h3><p>'+pct(r.p)+' chance of appearing × '+n(r.conditional_pa,2)+' PA if active = '+n(r.pa,2)+' expected PA. This is an average across possible seasons, not a promised workload.</p><p>Expected offense = '+n(r.pa,2)+' × ('+n(r.rate,4)+' batting /600 ÷ 600 + '+n(r.replacement_rate,8)+' replacement per PA) = '+n(r.value,3)+' custom offense wins. The point hitting center is learned with actual-PA weights; this does not assume two independent unweighted means.</p>';
html+='<h3>Same average, different uncertainty</h3><div class="tablewrap"><table><thead><tr><th>Distribution</th><th class="num">P10</th><th class="num">Median</th><th class="num">P90</th></tr></thead><tbody>'+Object.entries(lawNames).map(([key,label])=>'<tr'+(key===by('law').value?' class="range-emphasis"':'')+'><td>'+label+'</td>'+r.ranges[key].slice(0,3).map(v=>'<td class="num">'+n(v,3)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p>The ranges include a '+pct(1-r.p)+' chance of no MLB PA. A zero median or P90 is not a zero hitting-talent estimate. The new versions draw integer outs, walks and hits; the previous Normal law has '+pct(r.ranges.normal[5])+' physically impossible joint PA/offense mass.</p><p>Selected range: '+pct(range(r)[3])+' probability of negative offense and '+pct(range(r)[4])+' probability of at least two custom offense wins. These are not career-success or full-WAR probabilities.</p>';
html+='<h3>Evidence and omissions</h3><p>Organization: '+esc(r.org)+'. '+esc(r.team_basis)+'. '+esc(r.team_reason)+'. Last club: '+esc(r.club??'unknown')+', source year '+esc(r.club_year??'unknown')+'. Rights date: '+esc(r.rights_date??'no recorded override')+'. No current affiliation or target-season roster is used.</p><p>Distinct earlier matching people: '+n(r.participation_people)+' for appearance, '+n(r.workload_people)+' for active workload, '+n(r.calibration_people)+' for risk calibration. These are different profiles, not calibrated confidence percentages. Twenty is a warning threshold, not proof of enough comparable players.</p>';
html+='<ul>'+r.flags.map(f=>'<li class="warning">'+esc(f)+'</li>').join('')+'</ul><p>'+(r.draft_known?'Draft record: '+r.draft_year+', pick '+esc(r.pick_number)+', class '+esc(r.draft_class||'unknown')+'.':'No usable draft record; unknown signing bonus is not zero pedigree.')+' Current preseason rank: '+(r.scout_listed===1?'listed, rank score '+n(r.scout_rank_score,3):r.scout_listed===0?'not listed in the complete table; not a zero talent grade':'unknown listing coverage')+'.</p>';
html+='<h3>Actual source statistics available then</h3>'+historyTable(history[String(r.player_id)]||[])+'<p class="muted">Only the three origin history years are shown. Missing rows are not proof of zero talent or injury. No 2020 minor season existed; short-season MLB counts remain explicit. Bucket labels identify the source level, not a forecast of next year\'s level.</p>';
if(actual)html+='<h3>What happened in '+r.target_year+'</h3><p>'+n(r.next_pa)+' MLB PA; '+(r.next_rate==null?'hitting rate unobserved because he did not appear':n(r.next_rate,3)+' actual batting /600')+'; '+n(r.next_value,3)+' custom offense wins.</p>';
else html+='<p class="muted">Player outcomes and outcome-informed player reviews are hidden. Turn on “Show player results” to inspect them. Aggregate historical benchmarks remain visible below the player table.</p>';
html+='<details><summary>Exact model inputs and saved hitting contributions</summary><div id="trace">Loading saved-model evidence…</div></details>'+(actual&&r.reviewed?'<h3>Completed player walkthrough</h3><div id="review" class="review">Loading reviewed evidence…</div>':'');
by('detailBody').innerHTML=html;if(open&&!by('detail').open)by('detail').showModal();
try{const z=await get('details/'+r.row_id+'.json');if(token!==detailToken)return;
z.rate_terms=meta.rate_features.map((name,i)=>[name,z.rate_inputs[i],z.rate_contributions[i]]).sort((a,b)=>Math.abs(b[2])-Math.abs(a[2]));
z.opportunity_inputs=Object.fromEntries(meta.opportunity_features.map((name,i)=>[name,z.opportunity_inputs[i]]));
by('trace').innerHTML='<p>Saved Ridge intercept '+n(z.rate_intercept,6)+' plus all listed contributions = '+n(z.replayed_rate,6)+'. Contributions explain this fitted calculation, not causal effects.</p><div class="tablewrap"><table class="evidence-table"><thead><tr><th>Hitting input</th><th class="num">Scaled input</th><th class="num">Contribution</th></tr></thead><tbody>'+z.rate_terms.map(t=>'<tr><td>'+esc(t[0])+'</td><td class="num">'+n(t[1],5)+'</td><td class="num">'+n(t[2],5)+'</td></tr>').join('')+'</tbody></table></div><details><summary>All opportunity inputs</summary><div class="tablewrap"><table><thead><tr><th>Input</th><th class="num">Actual encoded value</th></tr></thead><tbody>'+Object.entries(z.opportunity_inputs).map(([k,v])=>'<tr><td>'+esc(k)+'</td><td class="num">'+n(v,6)+'</td></tr>').join('')+'</tbody></table></div></details><p>Risk concentration '+n(z.count_parameters.associated.phi,2)+', rate/workload slope '+n(z.count_parameters.associated.beta,4)+' (the declared upper bound), positive-workload log center '+n(z.workload_log_center,4)+'. The league reference mix is a working shape, not this player\'s own K/BB/HR projection.</p>';
if(actual&&r.reviewed){const review=await get('reviews/'+r.row_id+'.json');if(token!==detailToken)return;by('review').innerHTML='<p>'+esc(review.note)+'</p><p class="muted">Selected because: '+esc(review.selection.join('; '))+'. Outcome-selected cases are diagnostics, not independent validation.</p><h3>Comparisons selected without future outcomes</h3><div class="tablewrap"><table><thead><tr><th>Player</th><th class="num">Age</th><th class="num">Prior MLB PA</th><th class="num">Prior MiLB PA</th><th class="num">Actual next-year PA</th></tr></thead><tbody>'+review.peers.map(p=>'<tr><td>'+esc(p.player_name)+'</td>'+[p.age,p.pa_0,p.minor_pa_0,p.next_pa].map(v=>'<td class="num">'+n(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="muted">'+esc(review.peer_limit)+'</p>';}
}catch(e){if(token===detailToken&&by('trace'))by('trace').textContent='Evidence could not be loaded: '+e.message;}}
function explain(){by('modelCard').innerHTML=meta.model_card.map(p=>'<p>'+esc(p)+'</p>').join('');const p=meta.public_benchmark;
by('benchmark').innerHTML='<p>'+n(p.rows)+' identical public matches across seven target years. Lower errors are better. Years are equally weighted, and these are already-exposed development results.</p><div class="tablewrap"><table><thead><tr><th>Model</th><th class="num">PA RMSE</th><th class="num">PA average absolute error</th><th class="num">Custom offense RMSE</th></tr></thead><tbody>'+[['Current candidate','preseason'],['Earlier anchor','baseline'],['Steamer','steamer']].map(([label,key])=>'<tr><td>'+label+'</td>'+['pa_rmse','pa_mae','value_rmse'].map(k=>'<td class="num">'+n(p.scores[key][k],k==='value_rmse'?4:2)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div><p class="warning">Playing-time average absolute error remains '+n(100*(p.scores.preseason.pa_mae/p.scores.steamer.pa_mae-1),2)+'% worse than Steamer, outside the declared 15% allowance. Custom offense conversion has environment/date qualifications; the smaller displayed offense error is not proof of better hitting talent.</p><ul>'+meta.limits.map(p=>'<li>'+esc(p)+'</li>').join('')+'</ul>';
by('riskScores').innerHTML='<p>Mean P10/median/P90 pinball loss, equal weight per target year. Lower is better. Public projections do not provide matching ranges here.</p><div class="tablewrap"><table><thead><tr><th>Cohort</th><th class="num">Rows</th><th class="num">Previous Normal</th><th class="num">Independent counts</th><th class="num">Linked counts</th><th class="num">Expected PA</th><th class="num">Actual PA</th></tr></thead><tbody>'+meta.risk_scores.map(s=>'<tr><td>'+esc(s.scope)+'</td><td class="num">'+n(s.rows)+'</td>'+['normal','independent','associated'].map(a=>'<td class="num">'+n(s.scores[a].pinball,6)+'</td>').join('')+'<td class="num">'+n(s.expected_pa)+'</td><td class="num">'+n(s.actual_pa)+'</td></tr>').join('')+'</tbody></table></div><p>About .4% range-error improvement overall. All 35 linked slopes reached the declared limit. Physical coherence is verified; full-population calibration and point-forecast accuracy are not established.</p>';}
by('rows').addEventListener('click',e=>{const b=e.target.closest('[data-row]');if(b)detail(data.find(r=>r.row_id===+b.dataset.row));});
for(const id of ['org','stage','evidence','law'])by(id).addEventListener('change',()=>render());by('search').addEventListener('input',()=>render());
by('year').addEventListener('change',()=>{by('detail').close();currentRow=null;loadYear();});
by('actual').addEventListener('change',()=>{if(!by('actual').checked&&sort.startsWith('next_')){sort='value';descending=true;}render();});
for(const b of document.querySelectorAll('[data-sort]'))b.addEventListener('click',()=>{descending=sort===b.dataset.sort?!descending:b.dataset.sort!=='player_name';sort=b.dataset.sort;render();});
by('prev').onclick=()=>{page--;render(false);};by('next').onclick=()=>{page++;render(false);};by('close').onclick=()=>by('detail').close();
by('reset').onclick=()=>{for(const id of ['org','stage','evidence','search'])by(id).value='';by('law').value='associated';sort='value';descending=true;render();};
by('download').onclick=()=>{const actual=by('actual').checked,cols=['player_id','player_name','origin_year','target_year','org','stage','rate','p','conditional_pa','pa','value','calibration_people','range_law','offense_p10','offense_median','offense_p90','p_negative_offense','p_two_offense_wins',...(actual?['next_pa','next_rate','next_value']:[])];const cell=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const csv=[cols.join(','),...filtered.map(r=>{const a=range(r),exported={...r,range_law:by('law').value,offense_p10:a[0],offense_median:a[1],offense_p90:a[2],p_negative_offense:a[3],p_two_offense_wins:a[4]};return cols.map(k=>cell(exported[k])).join(',');})].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='hitter-research-'+by('year').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
async function hittingBenchmark(){try{const b=await get('hitting-benchmark.json');by('benchmark').insertAdjacentHTML('afterbegin','<h3>Hitting only</h3><p>'+n(b.active_rows)+' observed MLB seasons from the '+n(b.public_rows)+' identical public matches. Each year is equally weighted; within a year, hitting errors are weighted by actual PA. Non-arrivals remain in workload/value tests, but have no observed MLB hitting rate.</p><div class="tablewrap"><table><thead><tr><th>Model</th><th class="num">Batting /600 RMSE</th><th class="num">Average absolute error</th></tr></thead><tbody>'+[['Current candidate','baseline'],['Steamer','steamer'],['ZiPS','zips']].map(([label,key])=>'<tr><td>'+label+'</td><td class="num">'+n(b.rates[key].rmse,4)+'</td><td class="num">'+n(b.rates[key].mae,4)+'</td></tr>').join('')+'</tbody></table></div><p class="muted">All three use the same fixed-event conversion and origin league reference. These are not official WAR or verified park-neutral talent; retrospective snapshot dates and environment offsets qualify the comparison. ZiPS playing time is not treated as an equivalent workload forecast in the table below.</p><h3>Playing time and delivered offense</h3>');}catch(e){by('benchmark').insertAdjacentHTML('afterbegin','<p class="warning">Hitting benchmark could not be loaded: '+esc(e.message)+'</p>');}}
get('metadata.json').then(async z=>{meta=z;for(const y of meta.target_years.slice().reverse())by('year').add(new Option(y,y));explain();await loadYear();await hittingBenchmark();}).catch(e=>{by('loadError').textContent='Could not load the model metadata: '+e.message;});
