'use strict';
const by=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(x,d=0)=>x==null?'—':Number(x).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
const pct=x=>x==null?'—':num(100*x,1)+'%';
const norm=x=>String(x).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const pos=x=>({'1':'P','2':'C','3':'1B','4':'2B','5':'3B','6':'SS','7':'LF','8':'CF','9':'RF','10':'DH','Y':'OF'}[x]??x??'Unknown');
let meta,heads,data=[],history={},launch={},filtered=[],page=0,sort='rate',descending=true,loadToken=0,detailToken=0;
const size=40,cache=new Map();
async function get(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(path+' failed ('+r.status+')');return r.json();}
function options(id,values,label){const keep=by(id).value;by(id).replaceChildren(new Option(label,''));for(const v of values)by(id).add(new Option(v,v));if(values.includes(keep))by(id).value=keep;}
function value(r,key){if(key==='rate')return r.rates[by('arm').value];if(key==='value')return r.values[by('arm').value];if(key==='miss')return Math.abs(r.values[by('arm').value]-r.next_value);return r[key];}
function table(header,rows){return '<div class="tablewrap"><table><thead><tr>'+header.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
async function loadYear(){const token=++loadToken;by('loadError').textContent='';by('rows').innerHTML='<tr><td colspan="11">Loading…</td></tr>';try{const y=+by('year').value,z=await get('years/'+y+'.json');if(token!==loadToken)return;data=z.rows;history=z.history;launch=z.launch;options('org',[...new Set(data.map(r=>r.org))].sort(),'All organizations');options('stage',[...new Set(data.map(r=>r.stage))].sort(),'All stages');by('orgLabel').textContent=(y-1)+' organization (reconstructed)';by('timing').textContent='Predicting '+y+' from statistics through '+(y-1)+' and dated rankings through '+meta.information_dates[String(y)]+'. Organizations are origin reconstructions, not future teams. Unknown affiliations remain included.';render();}catch(e){if(token===loadToken){data=[];history={};launch={};by('loadError').textContent='Could not load data: '+e.message;render();}}}
function render(reset=true){if(reset)page=0;const actual=by('actual').checked,query=norm(by('search').value.trim()),org=by('org').value,stage=by('stage').value,evidence=by('evidence').value;
filtered=data.filter(r=>(!org||r.org===org)&&(!stage||r.stage===stage)&&(!query||norm(r.player_name).includes(query)||String(r.player_id).includes(query))&&(!evidence||(evidence==='reviewed'&&r.reviewed)||(evidence==='public'&&r.public_match)||(evidence==='sparse'&&(r.rate_profile_people==null||r.rate_profile_people<20))||(evidence==='untracked'&&r.mlb_ev_n===0)||(evidence==='minor'&&r.minor_comparison_enabled)));
filtered.sort((a,b)=>{const x=value(a,sort),y=value(b,sort);if(x==null)return y==null?a.row_id-b.row_id:1;if(y==null)return -1;const delta=typeof x==='string'?x.localeCompare(y):x-y;return (descending?-delta:delta)||a.row_id-b.row_id;});
const pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(Math.max(0,page),pages-1);document.querySelectorAll('.actualcol').forEach(el=>el.classList.toggle('hidden',!actual));
by('rows').innerHTML=filtered.slice(page*size,(page+1)*size).map(r=>'<tr><td><button class="player" data-row="'+r.row_id+'">'+esc(r.player_name)+'</button><span class="sub">'+esc(pos(r.position))+' · '+r.player_id+'</span></td><td>'+esc(r.stage)+'</td>'+['rate','p','pa','value'].map(k=>'<td class="num">'+(k==='p'?pct(r.p):num(value(r,k),['rate','value'].includes(k)?2:0))+'</td>').join('')+['next_pa','next_rate','next_value','miss'].map(k=>'<td class="num actualcol'+(!actual?' hidden':'')+'">'+num(value(r,k),k==='next_pa'?0:2)+'</td>').join('')+'<td><span class="sub">'+esc(r.branch)+'</span><span class="warning">'+r.flags.length+' warnings</span></td></tr>').join('')||'<tr><td colspan="11">No players match these filters.</td></tr>';
by('page').textContent=num(filtered.length)+' players · page '+(page+1)+' of '+pages;by('prev').disabled=page===0;by('next').disabled=page>=pages-1;
const sum=k=>filtered.reduce((a,r)=>a+value(r,k),0);by('totals').innerHTML=[['Players',filtered.length,0],['Expected PA',sum('pa'),0],['Expected batting contribution',sum('value'),2],...(actual?[['Actual PA',sum('next_pa'),0],['Actual batting contribution',sum('next_value'),2]]:[])].map(([label,x,d])=>'<p>'+label+'<strong>'+num(x,d)+'</strong></p>').join('');
by('comparison').textContent=by('arm').value.startsWith('precision_')?'Comparison only: not adopted. Incremental minor measurement gains remain uncertain, and some strong IL hitters receive questionable negative updates. Playing time is unchanged.':'';
for(const b of document.querySelectorAll('[data-sort]')){b.setAttribute('aria-sort',b.dataset.sort===sort?(descending?'descending':'ascending'):'none');b.textContent=b.textContent.replace(/ [↓↑]$/,'')+(b.dataset.sort===sort?(descending?' ↓':' ↑'):'');}}
function facts(items){return '<div class="facts">'+items.map(([name,v])=>'<div class="fact"><span>'+esc(name)+'</span><strong>'+esc(v)+'</strong></div>').join('')+'</div>';}
function terms(head,inputs){return head.features.map((name,i)=>[name,inputs[i],head.coefficients[i],inputs[i]*head.coefficients[i]]).sort((a,b)=>Math.abs(b[3])-Math.abs(a[3]));}
function traceTable(head,inputs){const t=terms(head,inputs),total=head.intercept+t.reduce((a,r)=>a+r[3],0);return '<p>Intercept '+num(head.intercept,6)+' + all contributions = '+num(total,6)+'. These are conditional fitted terms, not causal effects or changes versus the old forecast.</p>'+table(['Input','Encoded value','Coefficient','Contribution'],t.map(r=>[r[0],num(r[1],6),num(r[2],6),num(r[3],6)]));}
async function detail(r){const token=++detailToken,actual=by('actual').checked,arm=by('arm').value;by('detailTitle').textContent=r.player_name;by('detailSubtitle').textContent='Predicting '+r.target_year+' · '+r.org+' · '+r.stage+' · '+pos(r.position)+' · age '+num(r.age,1);by('detailBody').innerHTML=facts([['Selected hitting /600',num(r.rates[arm],3)],['Expected PA',num(r.pa)],['MLB PA chance',pct(r.p)],['PA if active',num(r.conditional_pa)],['Batting contribution',num(r.values[arm],3)],...(actual?[['Actual PA',num(r.next_pa)],['Actual hitting /600',num(r.next_rate,3)],['Actual contribution',num(r.next_value,3)]]:[])])+'<p>Main hitting branch: '+esc(r.branch)+'. Every comparison retains the same PA model. The conditional PA and hitting estimates are not guaranteed healthy-season talent or career value.</p>'+table(['Forecast','Hitting /600','Batting contribution'],Object.entries(meta.arms).map(([a,name])=>[name,num(r.rates[a],4),num(r.values[a],4)]))+'<h3>Warnings and actual training support</h3><ul>'+r.flags.map(f=>'<li>'+esc(f)+'</li>').join('')+'</ul><p>Earlier matching people: hitting '+num(r.rate_profile_people)+', appearance '+num(r.participation_people)+', active workload '+num(r.workload_people)+'. Definitions differ between components. Counts are warnings, not proof of equivalent players or calibrated uncertainty.</p><h3>Raw production known at the origin</h3>'+table(['Season','Level','PA','HR','K','UBB','2B','3B','H','AB','Team ID','League ID'],(history[r.player_id]||[]).map(h=>h.map((x,i)=>i===1?x:num(x))))+'<p class="muted">Separate dated stints; these are raw source counts, not automatically park-neutral or equal across levels. The fitted inputs below may pool and transform them.</p><h3>Available launch measurements</h3>'+table(['Season','Source / league','Measured EV','Measured EV + angle','EV coverage denominator','Mean EV mph','EV95 mph','Best-half EV mph','Mean angle','Hard-air share','Pair coverage'],(launch[r.player_id]||[]).map(h=>[h.season,h.source+(h.league_id?' / '+h.league_id:''),num(h.measured_ev_contacts),num(h.measured_pair_contacts),num(h.terminal_nonbunt_contacts),num(h.mean_ev,2),num(h.ev95,2),num(h.best_half_ev,2),num(h.mean_la,2),pct(h.hard_air_fraction),pct(h.pair_coverage)]))+'<p class="muted">Recent MLB EV samples '+num(r.mlb_ev_n)+'; minor EV samples '+num(r.minor_ev_n)+'. A small sample or missing measurement is not proof of poor talent. Raw minor measurements may be disabled by historical outcome support.</p><h3>Why this forecast happened</h3><div id="trace">Loading actual fitted inputs…</div>'+(actual&&r.reviewed?'<h3>Completed player reviews</h3><div id="review">Loading reviews…</div>':'');if(!by('detail').open)by('detail').showModal();
try{if(!cache.has(r.cell))cache.set(r.cell,await get('cells/'+r.cell+'.json'));if(token!==detailToken)return;const z=cache.get(r.cell).rows[String(r.row_id)],h=heads[r.cell];by('trace').innerHTML='<p>Main assembly uses '+esc(z.branch)+'. Saved head '+esc(h.rate[z.branch].sha256)+'.</p><details><summary>All main hitting inputs and contributions</summary>'+traceTable(h.rate[z.branch],z.rate_inputs)+'</details>'+Object.entries(z.adjustment_inputs).map(([a,x])=>'<details><summary>'+esc(meta.arms[a])+' — all adjustment terms</summary><p>Applied: '+(r.minor_comparison_enabled?'yes':'no; exact main fallback')+'. This is an additive adjustment, not the full hitting forecast.</p>'+traceTable(h.adjustments[a],x)+'</details>').join('')+'<details><summary>All actual opportunity inputs</summary>'+table(['Input','Encoded value'],meta.opportunity_features.map((name,i)=>[name,num(z.opportunity_inputs[i],6)]))+'</details><p>Saved raw appearance probability '+pct(r.raw_p)+' and raw active PA '+num(r.raw_conditional_pa,3)+'. The existing bounded/status rules produce '+pct(r.p)+' × '+num(r.conditional_pa,3)+' = '+num(r.pa,3)+' expected PA. Both raw heads were replayed for every exported row. The PA frame is preserved separately from newer translated hitting features.</p><p class="muted">No new uncertainty range is attached: earlier distributions were fitted around a different hitting mean. This view is one-year batting research, not full player value.</p>';
if(actual&&r.reviewed){const reviews=await get('reviews/'+r.row_id+'.json');if(token!==detailToken)return;by('review').innerHTML=reviews.map(c=>'<div class="review"><h3>'+esc(c.component)+'</h3><p>'+esc(c.note)+'</p><p class="muted">Selection: '+esc(c.selection.join('; '))+'. Cases selected by errors are diagnostics, not confirmation.</p>'+table(['Origin-selected peer','Age','Expected PA','Actual PA'],c.peers.map(p=>[p.player_name,num(p.age,1),num(p.preseason_pa??p.pa),num(p.next_pa)]))+'<p class="muted">Peers were selected from origin information; sample/role similarity does not certify equal talent.</p></div>').join('');if(reviews.some(c=>c.component==='MLB Statcast')){const n=await get('mlb-review.json');if(token!==detailToken)return;by('review').insertAdjacentHTML('beforeend','<details><summary>Complete MLB result and player narrative</summary><pre>'+esc(n.text)+'</pre></details>');}}
}catch(e){if(token===detailToken&&by('trace'))by('trace').textContent='Evidence could not load: '+e.message;}}
function explain(){by('modelCard').innerHTML=meta.model_card.map(t=>'<p>'+esc(t)+'</p>').join('')+'<ul>'+meta.limits.map(t=>'<li>'+esc(t)+'</li>').join('')+'</ul>';const p=meta.public_benchmark,v=meta.public_value;
by('benchmark').innerHTML='<p>'+num(p.rows)+' identical public matches. Lower errors are better. Years are equally weighted; sources have archive-date and environment-conversion qualifications.</p>'+table(['Forecast','PA RMSE','PA average absolute error','Converted batting-contribution RMSE'],[['Previous current',num(p.scores.preseason.pa_rmse,2),num(p.scores.preseason.pa_mae,2),num(p.scores.preseason.value_rmse,4)],['Main research assembly',num(p.scores.preseason.pa_rmse,2),num(p.scores.preseason.pa_mae,2),num(v.contribution.combined.rmse,4)],['Steamer',num(p.scores.steamer.pa_rmse,2),num(p.scores.steamer.pa_mae,2),num(p.scores.steamer.value_rmse,4)]])+'<p class="warning">PA average absolute error is '+num(100*(p.scores.preseason.pa_mae/p.scores.steamer.pa_mae-1),2)+'% worse than Steamer, outside the declared 15% allowance. Smaller converted batting-contribution error does not prove native WAR or park-neutral hitting superiority.</p><h3>All known players and origin-year checks</h3><p>Rate RMSE weights actual PA within equally weighted years and excludes unobserved zero-PA rates. Contribution retains non-arrivals. The actual totals below use the separate fixed-origin contribution reference.</p>'+table(['Scope','Forecasts','Main hitting RMSE','Old hitting RMSE','Main contribution RMSE','Actual contribution','Predicted contribution','Actual PA','Predicted PA'],meta.scores.filter(s=>s.scope==='all'||/^origin_/.test(s.scope)).map(s=>[s.scope,num(s.rows),num(s.participant_rate?.combined.rmse,4),num(s.participant_rate?.preseason.rmse,4),num(s.contribution.combined.rmse,4),num(s.actual_value,2),num(s.contribution.combined.predicted_total,2),num(s.actual_pa),num(s.predicted_pa)]));}
by('rows').addEventListener('click',e=>{const b=e.target.closest('[data-row]');if(b)detail(data.find(r=>r.row_id===+b.dataset.row));});
for(const id of ['org','stage','evidence','arm'])by(id).addEventListener('change',()=>{detailToken++;by('detail').close();render();});by('search').addEventListener('input',()=>render());by('year').addEventListener('change',()=>{detailToken++;by('detail').close();loadYear();});
by('actual').addEventListener('change',()=>{detailToken++;by('detail').close();if(!by('actual').checked&&(sort.startsWith('next_')||sort==='miss')){sort='rate';descending=true;}render();});
for(const b of document.querySelectorAll('[data-sort]'))b.addEventListener('click',()=>{descending=sort===b.dataset.sort?!descending:b.dataset.sort!=='player_name';sort=b.dataset.sort;render();});by('prev').onclick=()=>{page--;render(false);};by('next').onclick=()=>{page++;render(false);};by('close').onclick=()=>{detailToken++;by('detail').close();};
by('reset').onclick=()=>{for(const id of ['org','stage','evidence','search'])by(id).value='';by('arm').value='combined';sort='rate';descending=true;render();};
by('download').onclick=()=>{const actual=by('actual').checked,arm=by('arm').value,cols=['player_id','player_name','origin_year','target_year','org','stage','branch','forecast','rate','p','conditional_pa','pa','value','rate_profile_people',...(actual?['next_pa','next_rate','next_value']:[])];const cell=x=>'"'+String(x??'').replace(/"/g,'""')+'"';const csv=[cols.join(','),...filtered.map(r=>{const v={...r,forecast:arm,rate:r.rates[arm],value:r.values[arm]};return cols.map(k=>cell(v[k])).join(',');})].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='historical-hitter-'+by('year').value+'-'+arm+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
Promise.all([get('metadata.json'),get('heads.json')]).then(async ([m,h])=>{meta=m;heads=h;for(const y of m.target_years.slice().reverse())by('year').add(new Option(y,y));for(const [a,label] of Object.entries(m.arms))by('arm').add(new Option(label,a));by('arm').value=m.default_arm;explain();await loadYear();}).catch(e=>{by('loadError').textContent='Could not load metadata: '+e.message;});
